name: futuristreminder
description: A new Flutter project to Hack20!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  get: ^3.1.0  
  sqflite: ^1.3.1
  google_fonts: ^1.1.0
  flutter_screenutil: ^2.1.0
  image_picker: ^0.6.7+2
  image_cropper: ^1.2.3
  line_icons: ^0.2.0
  permission_handler: ^5.0.1+1
  geolocator: ^5.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

